language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO_VERSION=1.4.5
  - DJANGO_VERSION=1.5
install:
  - "pip install --use-mirrors Django==$DJANGO_VERSION"
  - "pip install --use-mirrors --editable ."
script: "django-admin.py test --settings=flows.tests.settings flows"
